# MODEL
model_name: "UMI"

# ---------------------------------------------------------------------------
#  Paths
# ---------------------------------------------------------------------------
data_dir:  "data/stocks/"     # Folder with per-ticker stocks CSVs        (general)
logs_dir: "logs/"             # Where checkpoints / logs are stored       (general)
initial_cash: 20000           # portfolio initial cash                    (portfolio)
currency: USD

# ---------------------------------------------------------------------------
#  Calendar – defines the walk-forward split
# ---------------------------------------------------------------------------
train_start:    2018-01-01  # First bar used for **Stage-1 factor learning**  (UMI paper §4.1)
train_end:      2020-12-31  # Last bar of training set
valid_end:      2021-06-30  # Final bar of validation set (early stopping / Optuna)
backtest_start: 2021-07-01  # First bar the strategy trades (“live simulation”)
backtest_end:   2023-07-01  # End of walk-forward evaluation (2 years)

# ---------------------------------------------------------------------------
#  Universe / data granularity
# ---------------------------------------------------------------------------
freq: 1B                      # 1 business-day bars (Lean offset code)    (common)
window_len: 60                # L : look-back window length (UMI paper)   (sliding-window features)
pred_len:   1                 # H : prediction horizon (next bar)         (one-step forecast)
dynamic_universe_mult: 0.2    # Capacity multiplier when extenting universe: 1+univers_mult (in this case ↑20%)       

# ---------------------------------------------------------------------------
#  Training schedule & hyper-param search
# ---------------------------------------------------------------------------
training:
  tune_hparams:   false      # Use Optuna Bayesian search                 
  n_trials:       20        # #Optuna trials for each run
  n_epochs:       20        # Full epochs on train+valid after tuning
  batch_size:     64        # Mini-batch size for AdamW                 
  training_mode:  sequential  # “sequential”: Stage-1 → Stage-2    /   “hybrid”  : Stage-1 (pretrain) → Stage-1 + Stage-2
  pretrain_epochs: 5        # Stage-1 warm-up epochs in hybrid mode
  patience:       10        # Early-stop patience 
  retrain_delta:  30        # Retrain every (30 * freq) bars


# ---------------------------------------------------------------------------
#  Warm-start fine-tune (optional quick pass after heavy fit)
# ---------------------------------------------------------------------------
warm_start:          true  # Enable warm-start                           (common in finance live rolls)
warm_training_epochs: 5    # Light fine-tune epochs


# ---------------------------------------------------------------------------
#  Default hyper-parameters (UMI paper, Table 2) – Optuna overwrites them
# ---------------------------------------------------------------------------
hparams:
  # λ_IC   : independence loss weight
  lambda_ic:         
    default: 0.5
    optuna:            
      type: categorical
      choices: [0, 0.25, 0.5, 0.75, 1]

  # λ_sync : synchronous factor loss 
  lambda_sync:
    default: 1.0
    optuna:
      type: categorical
      choices: [0, 0.5, 1, 1.5, 2]

  # λ_rank : rank-IC regulariser
  lambda_rankic:       
    default: 0.1
    optuna:
      type: categorical
      choices: [0, 0.05, 0.1, 0.15, 0.2]

  # τ : attention temperature
  temperature:
    default: 0.07
    optuna:
      type: float
      low: 0.03
      high: 0.2
  
  # θ_sync : threshold for stock synchrony
  sync_thr:
    default: 0.6
    optuna:
      type: float
      low: 0.5
      high: 0.8

  # α₁: learning-rate Stage-1 (AdamW)
  lr_stage1:
    default: 0.001
    optuna:
      type: log_float
      low: 1e-4
      high: 5e-3

  # α₁^ft  : LR when fine-tuning Stage-1 in hybrid mode
  lr_stage1_ft:
    default: 0.0001
    optuna:
      type: log_float
      low: 1e-5
      high: 1e-3

  # α₂: learning-rate Forecasting head
  lr_stage2:
    default: 0.0001
    optuna:
      type: log_float
      low: 1e-5
      high: 1e-3
  # stays frozen withouyt specifying the optuna values for hp optimization
  weight_decay: 0.0        

# ---------------------------------------------------------------------------
#  Allocation targets
# ---------------------------------------------------------------------------
allocation:
  gross_leverage: 2.0   # Σ|wᵢ|  ≤ 2  (1949 Graham “gross leverage”)
  net_exposure:   0.0   # Σwᵢ ≈ 0 (market-neutral)

selection:
  top_k: 30            # sell the worst 30 and buy the best the 30 stocks 

optimizer:
  name: max_sharpe               # maximize sharpe ratio
  lookback_days: 60              # history window to build the Σ matrix
#  allow_short:  true             # set false if you ever run long-only

# ---------------------------------------------------------------------------
#  Dataset n_bars loader
# ---------------------------------------------------------------------------
engine:
  cache:
    bar_capacity: 4096   # ≥ L + pred_len + some safety margin


# ---------------------------------------------------------------------------
#  Trading frictions
# ---------------------------------------------------------------------------
costs:
  fee_bps:    0.5          # One-way commission in basis-points of notional    (Tcost literature)
  prob_slippage: 0.2       # Simulates the probability of experiencing price slippage when executing market orders. When triggered, moves fill price one tick against your order direction
  prob_fill_on_limit: 0.2  # Simulates the probability of a limit order getting filled when its price level is reached in the market.New random probability check occurs each time market price touches your order price (but does not move through it)

# ---------------------------------------------------------------------------
#  Liquidity constraints
# ---------------------------------------------------------------------------
liquidity:
  adv_lookback: 30     # Look-back window to compute Average Daily Volume (ADV)
  max_adv_pct:  0.05   # Max trade size = 5 % ADV 

# ---------------------------------------------------------------------------
#  Execution parameters
# ---------------------------------------------------------------------------
execution:
  twap_slices: 4   # Split parent order into N TWAP child orders        

# ---------------------------------------------------------------------------
#  Risk management overlays
# ---------------------------------------------------------------------------
risk:
  trailing_stop_pct: 0.05      # 5 % trailing stop from HWM/LWM         
  target_vol_annual: 0.15      # Volatility target (Hull, risk parity) 15 %
  drawdown_pct:      0.15      # Kill-switch at 15 % peak-to-trough     (Kelly criterion risk control)
  max_weight_abs:    0.03      # Max 3 % NAV per single position        (concentration limit)
  max_weight_rel:    0.20      # Max 20 % of gross exposure in one name
  beta_neutral:                # Optional index-beta hedge 
    enabled: false
    benchmark: SPY            # Proxy for market factor (S&P 500 ETF)
    lookback_days: 60         # Regression window for beta estimation
    beta_tol: 0.02            # Allow residual β in ±0.02 band
